### ISSUE TITLE
Folding Herodoc

### ISSUE THREAD

**Issue by vitordm** [bobmagicii/vscode-auto-fold#2]
vscode-auto-fold does not working for herodoc strings.

**Comment by bobmagicii** [comment]
can code fold them normally? all this extension is doing is calling the fold.level built into the editor.

**Comment by vitordm** [comment]
If there is a herodoc inside the code, the fold does not working normally. It folds the code, but let herodoc showing.

**Comment by bobmagicii** [comment]
which language? in php i see that vscode cannot do heredoc at all unless its contents are indented. doesn't even show the little icon to manually fold it without the indent.

![here1](https://cloud.githubusercontent.com/assets/881944/23136057/9c9412e0-f760-11e6-825b-80c80a12c4de.png)

![here2](https://cloud.githubusercontent.com/assets/881944/23136061/9f81ac7e-f760-11e6-9c59-91035702eaea.png)

**Comment by vitordm** [comment]
PHP.

![image](https://cloud.githubusercontent.com/assets/4822277/23137677/2299b82e-f782-11e6-849c-d31886081e62.png)

**Comment by bobmagicii** [comment]
i feel pretty confident that the cause is code does not like that select being on the far left margin, then from and dual being one space over. the folding system in code seems to be purely based on detecting consistent indenting.

here is an example heredoc i'm using in a production project, and no matter what, code will just never ever fold it right.

![image](https://cloud.githubusercontent.com/assets/881944/23138585/e0b5d910-f76d-11e6-8216-0641992e429f.png)

![image](https://cloud.githubusercontent.com/assets/881944/23138577/d5c2930e-f76d-11e6-8058-391050e5d5b0.png)

**Comment by bobmagicii** [comment]
even trying to fold the entire class makes code lose its mind.

![image](https://cloud.githubusercontent.com/assets/881944/23138626/08fdf682-f76e-11e6-9ef5-d5b18b90e111.png)

**Comment by vitordm** [comment]
If I have a Heredoc String within my method. Should not It hide the string when I fold method?

**Comment by bobmagicii** [comment]
Heredoc is inherently messy, it is often better we avoid them. Obviously though, neither of us are.

All we can do is accept that Code cannot fold them properly since Heredoc close /must/ be on the right margin, or just not use them. I personally only use them within the Database migration scripts, never in the main application, because they are so messy.

This is not a problem unique to Code, most editors including Sublime text suffer the same issue.

![image](https://cloud.githubusercontent.com/assets/881944/23138978/dbfbe1f6-f76f-11e6-998a-b9c310d4f0cd.png)

**Comment by bobmagicii** [comment]
writing SQL in code is really hard, i got so mad at trying to format it well i wrote an entire library so i didn't have to write the SQL ;)

![image](https://cloud.githubusercontent.com/assets/881944/23139097/5eee89a6-f770-11e6-8249-281c61b275a1.png)

**Comment by vitordm** [comment]
Yes, i can see.

Sometimes we cannot avoid Heredoc. 
Thank you so much. I can see this plugin is very useful;

PS: Sorry for my English.
